### ISSUE TITLE
Need full example using Dragino LG01-P and TTN

### ISSUE THREAD

**Issue by spawnrider** [Bjoerns-TB/LoRaWAN-M5Stack#1]
Hi,

First of all, thanks for your work ! 

I just setted up a Dragino LG01 Lora Gateway.
I am stuck with the settings. 
My gateway is not receiving Lora packets from my M5Stack node :(

Could you show me a full example of how to send a message please ?

**Comment by Bjoerns-TB** [comment]
With the ABP.ino or OTAA.ino you have a full working example. The Sketch works with TTN and will send „Hallo World“. You only have to change the keys. Please also check the used frequency. AFAIK, the Dragino is not a full featured Gateway and will only work with one frequency.

**Comment by spawnrider** [comment]
Thanks a lot ! 

My m5stack module RHF76-052 version is 2.1.15. The join command is still failing...  How do you upgraded to the 2.1.19 version ? 

```
M5Stack initializing...OK
+VER: 2.1.15
+MODE: LWOTAA
+DR: EU868
+DR: DR5
+DR: EU868 DR5  SF7  BW125K
+CH: 0,868100000,DR0:DR5
+RXWIN1: 0,868100000
+POWER: 14
+PORT: 1
+JOIN: Start
+JOIN: NORMAL
+JOIN: Join failed
+JOIN: Done
+JOIN: No band in 87236ms

```

**Comment by Bjoerns-TB** [comment]
Hi,

the Dragino does not support OTAA, so you have to use ABP. [Dragino FAQ](https://wiki.dragino.com/index.php?title=LoRa_Questions#What_is_the_difference_between_LG01_single_channel_gateway_and_a_8-channel_LoRaWAN_gateway.3F)

If you want to youse OTAA with another Gateway you should uncomment these two lines:
  //lora.setDutyCycle(false);
  //lora.setJoinDutyCycle(false);

The Modem will start a join with SF12, so with enabled DutyCycle check, you have to wait for about 150s before another Join is possible.

You can update the firmware, but you dont‘t have to. Under the LoRaWAN printing are five solder pads. The pads give you access to the UART for firmware updates. On the back you can find theire meaning. You have to connect your PC with an USB to UART adapter. When you power on the module  you have to connect the EN pin with ground, which enables the DFU Mode. The rest is well described in the Seeeduino [Wiki](http://wiki.seeedstudio.com/Seeeduino_LoRAWAN/)

**Comment by spawnrider** [comment]
I just transmit some packets from my device to my gateway using ABP. 
Effectively, OTAA is not yet supported by the Dragino. This gateway is only for experimental purpose.

Thanks for your time and your precious help !

**Comment by Bjoerns-TB** [comment]
Glad i could help.
