### ISSUE TITLE
Format required for DevEUI, AppEUI and AppKey

### ISSUE THREAD

**Issue by patmolloy** [Bjoerns-TB/LoRaWAN-M5Stack#2]
The values produced by TTN for these are 8 bytes, 8 bytes and 16 bytes .. eg my DevEUI is 34567890ABCDEF01. Do these strings just go in as produced by TTN? The script compiles, but there is some kind kernel panic on the M5 and an endless reboot (and no Join).

Inserting these values as is below (i.e. 16 hex digits x 2 and then 32 hex digits for AppKey) does not wotk ...

// void setId(char *DevAddr, char *DevEUI, char *AppEUI);
  lora.setId(NULL, "1234567890", "1234567890");
  // setKey(char *NwkSKey, char *AppSKey, char *AppKey);
  lora.setKey(NULL, NULL, "12345678901234567890");

**Comment by Bjoerns-TB** [comment]
Yes the keys go in as produced by TTN, no changes here.

These are mine, the end is zeroed.
`  // void setId(char *DevAddr, char *DevEUI, char *AppEUI);
  lora.setId(NULL, "00EE583542E10000", "70B3D57ED0010000");
  // setKey(char *NwkSKey, char *AppSKey, char *AppKey);
  lora.setKey(NULL, NULL, "A8D113EBFF71C9FDD586796E7F730000");`

If you use an M5Stack Fire, please disable PSRAM under Boards settings, cause it collides with UART2.

**Comment by patmolloy** [comment]
Thanks! It's odd .. I am still stuck in my reboot loop :(

```
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:928
ho 0 tail 12 room 4
load:0x40078000,len:8424
ho 0 tail 12 room 4
load:0x40080400,len:5868
entry 0x4008069c
M5Stack initializing...OK
+VER: 2.1.15
+ID: DevAddr, 01:08:77:21
+ID: DevEui, 12:21:34:43:56:65:78:87
+ID: AppEui, 70:B3:D5:7E:D0:01:81:15
+ID: DevEui, 12:21:34:43:56:65:78:87
+ID: AppEui, 70:B3:D5:7E:D0:01:81:15
+KEY: APPKEY C0881C1C9006821DD⸮⸮?@?⸮⸮?
Stack smashing protect failure!

abort() was called at PC 0x400e11d4 on core 1

Backtrace: 0x40089164:0x3ffb1ea0 0x40089391:0x3ffb1ec0 0x400e11d4:0x3ffb1ee0 0x400d176b:0x3ffb1f00 0x400d1054:0x3ffb1f70 0x400d1102:0x3ffb1f90 0x400d7f07:0x3ffb1fb0 0x400852d9:0x3ffb1fd0

Rebooting...

```

These are the values I am trying to set ..

```
  // void setId(char *DevAddr, char *DevEUI, char *AppEUI);
  lora.setId(NULL, "1221344356657887", "70B3D57ED0018115");
  // setKey(char *NwkSKey, char *AppSKey, char *AppKey);
  lora.setKey(NULL, NULL, "C0881C1C9006821DDA07199BB7A7EEBD");
```

It looks like it's having a hard time with the AppKey ... based on the garbled display

**Comment by patmolloy** [comment]
This is using an M5Stack-Core

**Comment by Bjoerns-TB** [comment]
I tested it with the OTAA sketch and your keys and got it running immediately. 

> 

> M5Stack initializing...OK
> +VER: 2.1.19
> +ID: DevAddr, 26:01:1F:92
> +ID: DevEui, 00:EE:58:35:42:E1:0B:B1
> +ID: AppEui, 70:B3:D5:7E:D0:01:97:14
> +ID: DevEui, 12:21:34:43:56:65:78:87
> +ID: AppEui, 70:B3:D5:7E:D0:01:81:15
> +KEY: APPKEY C0881C1C9006821DDA07199BB7A7EEBD
> +MODE: LWOTAA
> +DR: EU868
> +DR: DR5
> +DR: EU868 DR5  SF7  BW125K
> +CH: 0,868100000,DR0:DR5
> +CH: 1,868300000,DR0:DR5
> +CH: 2,868500000,DR0:DR5
> +CH: 3,867100000,DR0:DR5
> +CH: 4,867300000,DR0:DR5
> +CH: 5,867500000,DR0:DR5
> +CH: 6,867700000,DR0:DR5
> +CH: 7,867900000,DR0:DR5
> +RXWIN1: 0,868100000
> +RXWIN2: 869500000,DR3
> +POWER: 14
> +PORT: 1
> +ADR: ON
> +JOIN: Start
> +JOIN: NORMAL
> +JOIN: Join failed
> +JOIN: Done
> +JOIN: Start
> +JOIN: NORMAL
> +JOIN: Network joined
> +JOIN: NetID 000013 DevAddr 26:01:21:61
> +JOIN: Done
> Started
> Sending
> +MSG: Start
> +MSG: Done
> Sent
> Sending


I will try it later with an M5Stack Core

**Comment by patmolloy** [comment]
Strange one. I tried on two different M5Stack Cores and got the same result.

I have ordered a Fire -- should be here today and will try with that. Perhaps my arduino setup is broken somewhere!

Thanks for looking :)

Pat


------ Original Message ------

**Comment by Bjoerns-TB** [comment]
Back from the lab.
It also works with the Core. It could be a connectipon problem. Try to apply some force from the top. The M5Stack headers can be a little bit frustrating.

**Comment by patmolloy** [comment]
Hmm. Most odd. Will give it a shot later ... I wonder if I have the right core/libraries installed??

Thanks for the help!

Pat


------ Original Message ------

**Comment by Bjoerns-TB** [comment]
If you follow [this guide](https://docs.m5stack.com/#/en/quick_start/m5core/m5stack_core_get_started_Arduino_Windows), you are on the right track, including this repo.

**Comment by patmolloy** [comment]
Thanks :)

------ Original Message ------

**Comment by patmolloy** [comment]
Hi Bjorn,

OK. So brand new fire today .. compiled the M5 Factory Test sketch and ran. Perfect.

Plugged in the blue lorawan board -- just just have the Fire and the Blue lorawan board .. recompiled Factory Test and loaded. Still fine.

Then I compile and load up the LoRaWAN OTAA sketch, and straight away I am back to my reboot loop that I had before.

Are we both using the same BLUE LoRaWAN module? With the AI-Thinker RHF76-052 chip?

It's possible my one is faulty in that case.

I'll also try the whole arduino install and setup on another machine, just to eliminate that!

Pat


------ Original Message ------

**Comment by Bjoerns-TB** [comment]
Hi Pat,

yes, we are both using the same module. The only difference is that i updated mine to version 2.19
Another thing you could try is disabling debug messages. In LoRaWan.cpp comment out while(SerialLoRa.available()) Serial.write(SerialLoRa.read());

**Comment by patmolloy** [comment]
Hi Bjorn,

Will look, thanks!

I tried the ABP script as well, same issue.

I did actually notice a few typos on the scripts up on Github .. I wonder if I am using the latest versions or whether you have updated?

  lora.setDeciveMode(LWOTAA); <<- Receive
  lora.setDataRate(DR5, EU868);

  lora.setChannel(0, 868.1);
  lora.setChannel(1, 868.3);
  lora.setChannel(2, 868.5);
  lora.setChannel(3, 867.1);
  lora.setChannel(4, 867.3);
  lora.setChannel(5, 867.5);
  lora.setChannel(6, 867.7);
  lora.setChannel(7, 867.9);

  lora.setReceiceWindowFirst(0, 868.1); << - Receive
  lora.setReceiceWindowSecond(869.525, DR3); <<- Receive

------ Original Message ------

**Comment by Bjoerns-TB** [comment]
Hi Pat,

that is the latest version. The original work was done by [Seeeduino](http://wiki.seeedstudio.com/Seeeduino_LoRAWAN/) and i modified it to work with the M5Stack. The typos are ok, cause the functions are named the same way, but i will fix this now.

**Comment by patmolloy** [comment]
I had to correct the typos to get it to compile actually, so it was not finding the functions at all. Strange! When I corrected, it compiled.

Pat


------ Original Message ------
