### ISSUE TITLE
lora.receivePacket

### ISSUE THREAD

**Issue by qvs5010** [Bjoerns-TB/LoRaWAN-M5Stack#3]
Hi 

Thanks for the scripts !!

I'm trying to read data send to the device.

```
    short length;
    short rssi;
    char buffer[256];
    memset(buffer, 0, 256);
    length = lora.receivePacket(buffer, 256, &rssi);
```

But when i try to compile i get the following error.

```
C:\Users\QLion\Documents\Arduino\libraries\M5Stack\src/LoRaWan.h:276:15: note: candidate: short int LoRaWanClass::receivePacket(char*, int, short int*, float*, short int*)

         short receivePacket(char *buffer, int length, short *rssi, float *snr, short *gwcnt);

               ^

C:\Users\QLion\Documents\Arduino\libraries\M5Stack\src/LoRaWan.h:276:15: note:   candidate expects 5 arguments, 3 provided

exit status 1
no matching function for call to 'LoRaWanClass::receivePacket(char [256], int, short int*)'

```

When i take a look at the Seeeduino script i see it only takes 3 perimeters, the new m5stack need 5.
(https://github.com/brady-aiello/Seeeduino_LoRaWAN_for_hybrid_gateways/blob/master/LoRaWan.cpp)

Do you know what i need to place in the other 2 perimeters 
` 'LoRaWanClass::receivePacket(char [256], int, short int*,**?** , **?**)'`

Thanks

**Comment by Bjoerns-TB** [comment]
Hi,

this should work:

      short length;
      short rssi;
      float snr;
      char charsnr[5];
      short gwcnt;

      memset(buffer, 0, 256);
      length = lora.receivePacket(buffer, 256, &rssi, &snr, &gwcnt);

      dtostrf(snr, 5, 1, charsnr);

**Comment by qvs5010** [comment]
Hi 

Thanks, that did the trick.

```
Sending
+MSG: Start
+MSG: PORT: 1; RX: "4AF8C28BAFEFF33162F0"
+MSG: RXWIN2, RSSI -69, SNR 4.8
+MSG: Done
1
Sent
4.80
Length is: 10
RSSI is: -69
Data is: 0x4A 0xF8 0xC2 0x8B 0xAF 0xEF 0xF3 0x31 0x62 0xF0 

```
