### ISSUE TITLE
Use this library with ttgo t-beam

### ISSUE THREAD

**Issue by geronimoooooooo** [Bjoerns-TB/LoRaWAN-M5Stack#4]
Hey,
Do you think it would be possible to use this library with the esp32 ttgo t-beam? What would be the rx and tx pins on the t-beam?

I have a t-beam and use the Lmic-arduino lib. It's way more complex than the LoRaWAN lib that is used for the m5stack.

**Comment by Bjoerns-TB** [comment]
Hi,
this won‘t work. The T-Beam uses an RFM95 which is connected via SPI bus. The RisingHF for the M5Stack uses UART. In addition these chips are totally differently to use.
Short said: no they are not compatible
