### ISSUE TITLE
Join failing on a successful connection

### ISSUE THREAD

**Issue by michaesc** [Bjoerns-TB/LoRaWAN-M5Stack#5]
## Hardware

I'm using a M5Stack core with a Lorawan module, original and recently bought (Summer 2020) from M5Stack. I updated the firmware of Lorawan to 2.1.19.

## Software

In PlatformIO I've replaced the files LoRaWan.cpp and LoRaWan.h as instructed. I have one source file in my program called main.cpp (which I renamed from OTAA.ino.) In my copy of this repository's OTAA.ino **I replaced the DevAddr and other identifiers** to match my TTN credentials.

After setting the ids correctly and lora.setDeviceMode(LWOTAA); lora.setDataRate(DR5, EU868); I see in my TTN dashboard:

```
Status
1 minutes ago
Frames up
0
Frames down
0
```

## Problem

...it seems **all is working correctly** with a green indicator (in the TTN dashboard for my device.) Except in my serial console I see:

```
+JOIN: Start
+JOIN: FORCE
+JOIN: Join failed
+JOIN: Done
```

## Question

What are some of the things I might try to resolve the failure and **correctly join the network?**

## Gateways

According to the TTN map, the nearest gateway is:

```
Placement: indoor
Brand: The Things Products
Model: The Things Gateway
Antenna model: unknown
```

...along with two more of further away distance, but those are Raspberry Pi based.

## Logging

A more detailed log of my serial console follows:

```
+VER: 2.1.19
+ID: DevAddr, XX:XX:XX:XX
+ID: DevEui, XX:XX:XX:XX:XX:XX:XX:XX
+ID: AppEui, XX:XX:XX:XX:XX:XX:XX:XX
+ID: DevAddr, XX:XX:XX:XX
+ID: DevEui, XX:XX:XX:XX:XX:XX:XX:XX
+ID: AppEui, XX:XX:XX:XX:XX:XX:XX:XX
+KEY: APPKEY XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
+MODE: LWOTAA
+DR: EU868
+DR: DR5
+DR: EU868 DR5  SF7  BW125K
+CH: 0,868100000,DR0:DR5
+CH: 1,868300000,DR0:DR5
+CH: 2,868500000,DR0:DR5
+CH: 3,867100000,DR0:DR5
+CH: 4,867300000,DR0:DR5
+CH: 5,867500000,DR0:DR5
+CH: 6,867700000,DR0:DR5
+CH: 7,867900000,DR0:DR5
+RXWIN1: 0,868100000
+RXWIN2: 869500000,DR3
+POWER: 14
+PORT: 1
+ADR: ON
+JOIN: Start
+JOIN: NORMAL
+JOIN: Join failed
+JOIN: Done
+JOIN: Start
+JOIN: NORMAL
+JOIN: Join failed
+JOIN: Done
+JOIN: Start
+JOIN: NORMAL
+JOIN: Join failed
+JOIN: Done
+JOIN: Start
+JOIN: NORMAL
+JOIN: Join failed
+JOIN: Done
```

**Comment by michaesc** [comment]
# Solved problem
Sorry for the lack of a pull request, because I don't know exactly which contstruct (ADR?, FirstWindow?, SecondWindow?, Join timeout?) is causing the problem.

## Solution

The following code is very similar to otaa.ino, however it works in my configuration and the **join failures** do not appear.

```
#include <M5Stack.h>
#include <LoRaWan.h>

unsigned char data[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 0xA,};
char buffer[256];

void setup(void)
{
    SerialUSB.begin(115200);
    while(!SerialUSB);
    
    lora.init();
    
    memset(buffer, 0, 256);
    lora.getVersion(buffer, 256, 1);
    SerialUSB.print(buffer); 
    
    memset(buffer, 0, 256);
    lora.getId(buffer, 256, 1);
    SerialUSB.print(buffer);

    SerialUSB.println("\nSetting keys...");
    // setKey(char *NwkSKey, char *AppSKey, char *AppKey)
    lora.setId(NULL, "XXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXX");
    lora.setKey(NULL, NULL, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    
    lora.setDeviceMode(LWOTAA);
    
    lora.setDataRate(DR0, EU868);
    
    lora.setChannel(0, 868.1);
    lora.setChannel(1, 868.3);
    lora.setChannel(2, 868.5);
    lora.setChannel(3, 867.1);
    lora.setChannel(4, 867.3);
    lora.setChannel(5, 867.5);
    lora.setChannel(6, 867.7);

    lora.setPower(14);
    
    while(!lora.setOTAAJoin(JOIN));

    // Give it some time to join the network
    // To prevent "LoRaWAN modem is busy" messages
    SerialUSB.println("Joined network, waiting for modem...");
    delay(5000);
}

void loop(void)
{   
    bool result = false;
    
    result = lora.transferPacket("Halloooo Welt!", 10);
    
    if(result)
    {
        short length;
        short rssi;
        float noise;
        short count;
        
        memset(buffer, 0, 256);
        length = lora.receivePacket(buffer, 256, &rssi, &noise, &count);
        
        if(length)
        {
            SerialUSB.print("Length is: ");
            SerialUSB.println(length);
            SerialUSB.print("RSSI is: ");
            SerialUSB.println(rssi);
            SerialUSB.print("Data is: ");
            for(unsigned char i = 0; i < length; i ++)
            {
                SerialUSB.print("0x");
                SerialUSB.print(buffer[i], HEX);
                SerialUSB.print(" ");
            }
            SerialUSB.println();
        }
    }
    delay(5000);
}
```

**Comment by Bjoerns-TB** [comment]
I think its related to the configuration.
My example sketch will try a network join with DR5 (SF7). Your example uses DR0 (SF12). SF12 is far more robust and you will achive higher distances , but will also increase your airtime dramatically. You can try lowering the datarate, to the last point where you are are able to join. 
With SF7 yout airtime is about 60ms, and with SF12 over one second. So you will ran into a legal problem. Normally the duty cycle is 1% in EU. TTN limits this to 30 seconds (actually not enforced), which gives you about 20 messages per day.
